### ISSUE TITLE
Is there a way to manually re-trigger the getter?

### ISSUE THREAD

**Issue by felixakiragreen** [sveltetools/svelte-asyncable#9]
My use-case:

I'm fetching a list of events from an API.

Separately, I've subscribed to another service which triggers a notification when there are new events.

**After** I've received the notification, I want to re-fetch the list of events, which should now have the new one, which will update the UI.

**Comment by PaulMaly** [comment]
Hi @felixakiragreen ! Sorry for the late answer, I'd missed it somehow or forgot about it. 

Anyway, I'll try to produce your situation using `svelte-asyncable` and [svelte-streamable](https://github.com/sveltetools/svelte-streamable) (SSE store):

```javascript
import { streamable } from 'svelte-streamable';
import { asyncable } from 'svelte-asyncable';

const eventsNotifier = streamable({ 
    url: 'http://xxx.xxx.xxx:xxx/notifications',
    event: 'events',
});
...
const events = asyncable(fetchEvents, null, [ eventsNotifier ]);
...
```

So, that's it. Every time when `eventsNotifier` store will be changed it will re-call `events` store `getter` because it's specified as a dependency of `asyncable` store. I'm sure you use another tool for your notifications, but still you can create a regular `writable/readable` store and pass it in 3rd argument of `asyncable` store. Anytime dependant stores have changed, asyncable `getter` will be performed automatically with new values of that stores.

Hope I'm answered your question, better late than never.

**Comment by felixakiragreen** [comment]
Thank you! This is exactly what I needed.
